name: Teste Automatizado

on:
  schedule:
    - cron: "0 7 * * *"
    - cron: "0 14 * * *"
    - cron: "0 19 * * *"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

  send-email:
    needs: [build-and-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Enviar e-mail
        run: |
          # Comandos para enviar o e-mail usando o arquivo YAML separado
          ./send-email.yml
