name: Teste Automatizado

on:
  schedule:
    - cron: "0 7 * * *"
    - cron: "0 14 * * *"
    - cron: "0 19 * * *"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      # Restante dos passos do seu fluxo de trabalho (configuração, instalação do Cypress, execução dos testes, etc.)
